export default {
	ADD_REMOTE_MESSAGE: 'ADD_REMOTE_MESSAGE',
	ADD_SELF_MESSAGE: 'ADD_SELF_MESSAGE',
	UPDATE_ROOMS: 'UPDATE_ROOMS',
	SET_ROOM: 'SET_ROOM',
	SET_NAME: 'SET_NAME',
	UPDATE_PROFILE: 'UPDATE_PROFILE',
	CONTACT_TYPING: 'CONTACT_TYPING',
	CONTACT_JOIN: 'CONTACT_JOIN',
	SET_CONTACT_LIST: 'SET_CONTACT_LIST',
};
