export default {
	SET_ACTIVE_CHANNEL: 'SET_ACTIVE_CHANNEL',
	SET_CHANNELS: 'SET_CHANNELS',
	CHANNEL_TYPING: 'CHANNEL_TYPING',
	CHANNEL_JOIN: 'CHANNEL_JOIN',
	CHANNEL_REMOVE: 'CHANNEL_REMOVE',
	SET_CHANNEL_LIST: 'SET_CHANNEL_LIST',
	ADD_CHANNEL: 'ADD_CHANNEL',
	SET_CHANNEL_ONLINE: 'SET_CHANNEL_ONLINE',
	SET_CHANNEL_OFFLINE: 'SET_OFFLINE_ONLINE',
	ADD_MESSAGE_TO_CHANNEL: 'ADD_MESSAGE_TO_CHANNEL',
	READ_MESSAGES: 'READ_MESSAGES'
};
